<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT2bY7AT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT2bY7AT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT2bY7AT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT2bY7AT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerT2bY7AT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'T2bY7AT',
    'container.build_id' => 'f37fab51',
    'container.build_time' => 1563902655,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT2bY7AT');
